version: '3.8'

services:
  password-checker:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./static:/app/static
      - ./templates:/app/templates
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    
  # Development version with hot reload
  password-checker-dev:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: ["python", "app.py"]
    profiles:
      - dev